import uuid
import json
import logging
import sys
from datetime import datetime
from typing import Dict, List, Optional
from pydantic import BaseModel, Field, ValidationError

# =================================================================
# OBSERVABILITY LAYER: Structured Logging Configuration
# =================================================================
class JsonFormatter(logging.Formatter):
    """Custom formatter to emit logs as JSON Lines (JSONL) for Grafana/Loki consumption."""
    def format(self, record):
        log_entry = {
            "timestamp": datetime.utcfromtimestamp(record.created).isoformat() + "Z",
            "level": record.levelname,
            "trace_id": getattr(record, 'trace_id', 'N/A'),
            "message": record.getMessage(),
            "metadata": getattr(record, 'metadata', {})
        }
        return json.dumps(log_entry)

logger = logging.getLogger("proSIM")
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(JsonFormatter())
logger.addHandler(handler)
logger.setLevel(logging.INFO)

# =================================================================
# AI RELIABILITY LAYER: Pydantic Data Contracts
# =================================================================
class SimulationEvent(BaseModel):
    """
    Ensures that LLM outputs adhere to strict business rules.
    Prevents hallucinations by validating metric deltas.
    """
    narrative: str = Field(..., description="The story beat generated by the AI.")
    delta_morale: float = Field(..., ge=-1.0, le=1.0, description="Morale change.")
    delta_trust: float = Field(..., ge=-1.0, le=1.0, description="Trust change.")
    hidden_risk_flag: bool = Field(default=False, description="Whether this decision triggered a system risk.")

class SimulationState(BaseModel):
    """The immutable state of the 'Physics Engine'."""
    session_id: str
    turn: int = 0
    health: float = 1.0
    trust: float = 0.5
    morale: float = 0.8
    revenue: float = 10000.0

# =================================================================
# EXECUTION LAYER: Headless State Machine
# =================================================================
class SimulationController:
    def __init__(self):
        self.state = SimulationState(session_id=str(uuid.uuid4()))
        self.trace_id = str(uuid.uuid4())

    def apply_event(self, event: SimulationEvent):
        """Enforcing deterministic state transitions."""
        pre_state = self.state.model_copy()
        
        # Physics Calculation
        self.state.morale = max(0.0, min(1.0, self.state.morale + event.delta_morale))
        self.state.trust = max(0.0, min(1.0, self.state.trust + event.delta_trust))
        self.state.turn += 1

        # Observability: Emit Structured Event
        logger.info(
            f"Turn {self.state.turn} Executed",
            extra={
                "trace_id": self.trace_id,
                "metadata": {
                    "action": event.narrative[:30] + "...",
                    "deltas": {"morale": event.delta_morale, "trust": event.delta_trust},
                    "state_snapshot": self.state.model_dump()
                }
            }
        )

    def mock_llm_call(self, user_input: str) -> str:
        """
        Simulates an LLM returning JSON. 
        In production, this would use litellm.completion().
        """
        # Mocking a generative response based on input
        if "growth" in user_input.lower():
            return json.dumps({
                "narrative": "You launched an aggressive ad campaign.",
                "delta_morale": -0.1,
                "delta_trust": 0.2,
                "hidden_risk_flag": False
            })
        return json.dumps({
            "narrative": "You focused on technical debt.",
            "delta_morale": 0.1,
            "delta_trust": -0.05,
            "hidden_risk_flag": False
        })

# =================================================================
# MAIN BOOTSTRAP
# =================================================================
def main():
    controller = SimulationController()
    
    logger.info("proSIM Engine Initialized", extra={"trace_id": controller.trace_id, "metadata": controller.state.model_dump()})

    # Example Game Loop
    print("\n--- proSIM Headless Engine CLI ---")
    print("Commands: 'growth', 'stability', 'exit'")
    
    while True:
        user_choice = input("\nDecision > ")
        if user_choice.lower() == 'exit': break

        # 1. AI Reasoning Phase (Mocked)
        raw_json = controller.mock_llm_call(user_choice)

        try:
            # 2. Validation Phase (Reliability)
            event = SimulationEvent.model_validate_json(raw_json)
            
            # 3. Execution Phase (Clarity)
            controller.apply_event(event)
            
            print(f"\n[NARRATIVE]: {event.narrative}")
            print(f"[VITALS]: Morale {controller.state.morale:.2f} | Trust {controller.state.trust:.2f}")

        except ValidationError as e:
            logger.error("LLM Schema Violation Detected", extra={"trace_id": controller.trace_id, "metadata": {"errors": e.errors()}})
            print("\n[ERROR]: AI Hallucination detected. State transition blocked.")

if __name__ == "__main__":
    main()